-- Real Seed Data

-- PROJECTS
DELETE FROM projects;
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    1, 'ahwa-saas-platform', 'published', true,
    'Ahwa — Café Operating System', 'أهوه — نظام تشغيل المقهى',
    'A full-stack multi-tenant SaaS OS engineered from the ground up for café operations.', 'نظام تشغيل SaaS متعدد المستأجرين مبني من الصفر لإدارة المقاهي بالكامل.',
    'A specialized operating system and management platform for cafes.', 'نظام تشغيل وإدارة مخصص للمقاهي.',
    'SaaS café management system', 'نظام إدارة مقاهي SaaS',
    'Ahwa — SaaS Café Operating System | El Hussainy', 'أهوه — نظام تشغيل مقاهي SaaS | الحسيني',
    'Multi-tenant SaaS platform for café management with shift control, inventory, QR ordering, full reporting, and role-based access for every staff member.', 'منصة SaaS متعددة المستأجرين لإدارة المقاهي مع التحكم في الورديات والمخزون والطلبات عبر QR والتقارير الشاملة وصلاحيات مبنية على الأدوار.',
    '["Next.js","PostgreSQL","Supabase"]'::jsonb, '["SaaS","Multi-tenant","Full-Stack","PostgreSQL","Management"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Ahwa Dashboard"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A specialized operating system and management platform for cafes.', 'نظام تشغيل وإدارة مخصص للمقاهي.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • PostgreSQL • Supabase', 'Next.js • PostgreSQL • Supabase',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    2, 'freelawyers-platform', 'published', true,
    'Freelawyers', 'Freelawyers',
    'A two-sided legal marketplace with escrow payments, offer lifecycle, dispute resolution, and dynamic lawyer ranking.', 'سوق قانوني ثنائي الأطراف مع مدفوعات الضمان، دورة حياة العروض، حل النزاعات، وتصنيف ديناميكي للمحامين.',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'legal marketplace platform', 'منصة سوق قانوني',
    'Freelawyers — Legal Marketplace Platform | El Hussainy', 'Freelawyers — منصة سوق قانوني | الحسيني',
    'Full-stack legal gig marketplace with role-based auth, request lifecycle, escrow payments, real-time chat, dispute resolution, and automatic lawyer ranking.', 'منصة سوق قانوني كاملة مع مصادقة مبنية على الأدوار، دورة حياة الطلبات، مدفوعات الضمان، دردشة فورية، حل النزاعات، وتصنيف تلقائي للمحامين.',
    '["Next.js 14","TypeScript","Supabase","PostgreSQL","RLS","Real-time"]'::jsonb, '["Marketplace","Legal","SaaS","Escrow","Full-Stack"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project2/cover.jpg","alt":"Freelawyers App"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Next.js 14 • TypeScript • Supabase • PostgreSQL • RLS • Real-time', 'Next.js 14 • TypeScript • Supabase • PostgreSQL • RLS • Real-time',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    3, 'lakatat-platform-rescue', 'published', true,
    'Lakatat — Platform Rescue', 'منصة لقطات — عملية الإنقاذ',
    'Inherited a broken media platform. Rebuilt the entire backend, shipped 16 new features, and turned a liability into a revenue-generating product.', 'استلمت منصة ميديا معطلة. أعدت بناء الخوادم بالكامل، أطلقت 16 ميزة جديدة، وحوّلت العبء إلى منتج يحقق أرباحًا.',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'video platform development FastAPI', 'تطوير منصة فيديو FastAPI',
    'Lakatat Media Platform Rescue | El Hussainy', 'إنقاذ منصة لقطات الإعلامية | الحسيني',
    'Rescued a broken FastAPI + React video platform: fixed black screens, rebuilt admin, added stories, playlists, comments, likes, AdSense, and multi-tenant role management.', 'إنقاذ منصة فيديو FastAPI + React معطلة: إصلاح الشاشات السوداء، إعادة بناء الأدمن، إضافة القصص والقوائم والتعليقات والإعجابات وAdSense وإدارة الأدوار.',
    '["FastAPI","Python","React","Vite","PostgreSQL","SQLAlchemy","Alembic","Redux"]'::jsonb, '["Rescue","Media","FastAPI","Full-Stack"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project7/cover.jpg","alt":"Lakatat Platform"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'FastAPI • Python • React • Vite • PostgreSQL • SQLAlchemy • Alembic • Redux', 'FastAPI • Python • React • Vite • PostgreSQL • SQLAlchemy • Alembic • Redux',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    4, 'nilu-tourism', 'published', false,
    'Nilu Tourism', 'نظام شركة Nilu للسياحة',
    'A private booking system built around the company’s way of working', 'نظام حجوزات خاص مصمم حول طريقة عمل الشركة نفسها',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'tourism management platform', 'منصة إدارة سياحة',
    'Nilu Tourism | Private Booking & Management System', 'نظام Nilu | محرك حجوزات متكامل لشركات السياحة',
    'A complete booking engine and operations dashboard developed for Nilu tourism, allowing end-to-end management of client itineraries.', 'محرك حجوزات ولوحة تشغيل متكاملة لشركة Nilu السياحية، تتيح إدارة رحلات العملاء وعمليات الحجز من البداية للنهاية.',
    '["Next.js","Booking Engine","Dashboard"]'::jsonb, '["Booking","Tourism","Fullstack"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project3/cover.jpg","alt":"NilU Platform"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Next.js • Booking Engine • Dashboard', 'Next.js • Booking Engine • Dashboard',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    5, 'al-ola-oil-collection', 'published', false,
    'AL OLA Oil Collection', 'منصة العلا لتجميع الزيت',
    'From informal collection to a trusted digital logistics network', 'من الجمع غير الرسمي إلى شبكة لوجستية رقمية موثوقة',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'logistics PWA oil collection', 'تطبيق لوجستيات تجميع زيت PWA',
    'AL OLA | Logistics App for Oil Collection', 'منصة العلا | تطبيق لوجستي ذكي لتجميع الزيت',
    'A robust logistics and collection web application functioning like Uber for used oil collection, featuring a comprehensive ERP and CRM dashboard.', 'تطبيق لوجستي ذكي يعمل بنظام مشابه لأوبر لتجميع الزيت المستهلك، مدعوم بلوحة تحكم ERP و CRM شاملة لإدارة الأسطول والمناديب.',
    '["Next.js","Maps API","ERP Integration","PostgreSQL"]'::jsonb, '["Logistics","ERP","CRM","Web App"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project5/cover.jpg","alt":"AL OLA App"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Next.js • Maps API • ERP Integration • PostgreSQL', 'Next.js • Maps API • ERP Integration • PostgreSQL',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    6, 'bcc-fullstack', 'published', false,
    'BCC Commercial', 'شركة BCC التجارية',
    'A luxury digital front for a high-profile agency', 'واجهة رقمية فاخرة لوكالة ذات مكانة عالية',
    'Built a complete platform from scratch, including dashboard and database (Fullstack).', 'إنشاء منصة كاملة من الصفر، تشمل لوحة التحكم وقواعد البيانات (Fullstack).',
    'multi-channel marketing communication hub', 'محور اتصالات تسويقية متعدد القنوات',
    'BCC Commercial | Luxury Agency Portal & Dashboard', 'شركة BCC التجارية | منصة رقمية فاخرة ولوحة تحكم',
    'A full-stack React and Supabase platform for BCC Commercial in KSA, featuring luxury UI and dynamic service management.', 'منصة متكاملة لشركة BCC التجارية في السعودية باستخدام React و Supabase، تتميز بواجهة جذابة ولوحة تحكم قوية لإدارة الخدمات والمنتجات.',
    '["Next.js","Node.js","PostgreSQL"]'::jsonb, '["Fullstack","Admin Dashboard","Luxury UI","Agency"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project3/cover.jpg","alt":"BCC Dashboard"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'Built a complete platform from scratch, including dashboard and database (Fullstack).', 'إنشاء منصة كاملة من الصفر، تشمل لوحة التحكم وقواعد البيانات (Fullstack).',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • Node.js • PostgreSQL', 'Next.js • Node.js • PostgreSQL',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    7, 'framemasters', 'published', false,
    'Framemasters', 'Framemasters',
    'Hardened a Lovable-built platform with strict Supabase RLS policies and live payment gateway integration.', 'تحصين منصة مبنية بـ Lovable بسياسات RLS صارمة في Supabase ودمج بوابة دفع حية.',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'Supabase RLS security payment integration', 'أمان Supabase RLS ودمج الدفع',
    'Framemasters — Security & Payment Integration | El Hussainy', 'Framemasters — أمان ودمج دفع | الحسيني',
    'Implemented strict Supabase Row Level Security and live payment gateway integration for a Lovable-built platform.', 'تطبيق Supabase Row Level Security الصارم ودمج بوابة الدفع الحية لمنصة مبنية بـ Lovable.',
    '["Supabase","PostgreSQL RLS","Payment Gateway APIs","TypeScript"]'::jsonb, '["Security","Integration","Supabase"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Framemasters"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Supabase • PostgreSQL RLS • Payment Gateway APIs • TypeScript', 'Supabase • PostgreSQL RLS • Payment Gateway APIs • TypeScript',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    8, 'growlik-seo', 'published', true,
    'GrowLik SEO', 'GrowLik — تحسين محركات البحث',
    'Page 1 Google Ranking Success', 'نجاح تصنيف الصفحات الأولى على Google',
    'Completely revamped site content and added 8 pages to optimize services and rank first in search results.', 'تغيير محتوى الموقع بالكامل وعمل 8 صفحات إضافية لتحسين المحتوى وتفصيل الخدمات لتصدر نتائج البحث الأولى.',
    'technical SEO WordPress performance', 'WordPress SEO تقني أداء',
    'GrowLik — Technical SEO Platform | El Hussainy', 'GrowLik — منصة SEO التقني | الحسيني',
    'WordPress platform engineered for Google page-one rankings through Core Web Vitals optimisation, JSON-LD schema injection, and performance-first architecture.', 'منصة WordPress مهندَسة لتصنيفات الصفحة الأولى بجوجل من خلال تحسين Core Web Vitals وحقن JSON-LD ومعمارية الأداء أولًا.',
    '["SEO","Content Strategy"]'::jsonb, '["SEO","Marketing","Ranking"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/growlik/cover.jpg","alt":"GrowLik SEO Results"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'Completely revamped site content and added 8 pages to optimize services and rank first in search results.', 'تغيير محتوى الموقع بالكامل وعمل 8 صفحات إضافية لتحسين المحتوى وتفصيل الخدمات لتصدر نتائج البحث الأولى.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'SEO • Content Strategy', 'SEO • Content Strategy',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    9, 'pos-system-nextjs', 'published', false,
    'Next.js POS & ERP System', 'نظام نقاط البيع POS و ERP',
    'Hardware-Integrated Point of Sale', 'نظام نقاط بيع متصل بالهاردوير',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'browser-based POS system', 'نظام POS قائم على المتصفح',
    'Advanced POS & ERP System built with Next.js', 'نظام نقاط بيع (POS) و ERP متقدم باستخدام Next.js',
    'A highly scalable POS software with a built-in ERP and Kitchen Display System, seamlessly integrated with retail hardware.', 'برنامج نقاط بيع قابل للتوسع يضم نظام ERP متكامل وشاشة مطبخ (KDS)، مع دعم كامل للأجهزة كطابعات الكاشير والباركود.',
    '["Next.js","ERP Integration","Hardware API"]'::jsonb, '["POS","ERP","SaaS","Hardware"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project4/cover.jpg","alt":"POS System"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Next.js • ERP Integration • Hardware API', 'Next.js • ERP Integration • Hardware API',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    11, 'rose-ecommerce', 'published', true,
    'Custom PHP E-Commerce (Noda, Gedo, Rose)', 'متجر إلكتروني مخصص (Noda, Gedo, Rose)',
    'PHP/MySQL Multi-Tenant E-Commerce', 'تجارة إلكترونية متعددة المستأجرين باستخدام PHP/MySQL',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'headless WooCommerce Next.js storefront', 'WooCommerce مفصولة الرأس Next.js',
    'Rose Store — Headless WooCommerce | El Hussainy', 'متجر روز — WooCommerce مفصولة الرأس | الحسيني',
    'Luxury beauty e-commerce built as headless WooCommerce on Next.js with sub-0.8s load time, ISR caching, and mobile-first luxury UX.', 'تجارة إلكترونية تجميل فاخرة مبنية كـ WooCommerce مفصولة الرأس على Next.js مع وقت تحميل أقل من 0.8 ثانية وISR caching وتجربة فاخرة للجوال أولًا.',
    '["PHP","MySQL","HTML","CSS"]'::jsonb, '["E-Commerce","PHP","Dashboard"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Rose Store"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'PHP • MySQL • HTML • CSS', 'PHP • MySQL • HTML • CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    12, 'al-afkham-woocommerce', 'published', false,
    'Al Afkham Store', 'متجر الأفخم',
    'Premium WooCommerce Experience', 'تجربة WooCommerce مميزة',
    'A complete WordPress WooCommerce project.', 'مشروع ووردبريس ووكمرس متكامل.',
    'WooCommerce luxury perfume store', 'متجر عطور فاخر WooCommerce',
    'Al Afkham — Luxury WooCommerce Perfume Store | El Hussainy', 'الأفخم — متجر عطور WooCommerce فاخر | الحسيني',
    'Bespoke WooCommerce luxury perfume boutique with Elementor Pro, Polylang multilingual, LiteSpeed performance, and premium dark-mode design.', 'بوتيك عطور WooCommerce فاخر مخصص مع Elementor Pro وPolylang متعدد اللغات وأداء LiteSpeed وتصميم وضع مظلم راقٍ.',
    '["WordPress","WooCommerce","PHP"]'::jsonb, '["E-Commerce","WordPress"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project6/cover.jpg","alt":"Al Afkham Store"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A complete WordPress WooCommerce project.', 'مشروع ووردبريس ووكمرس متكامل.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'WordPress • WooCommerce • PHP', 'WordPress • WooCommerce • PHP',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    13, 'arab-anglais', 'published', false,
    'Arab Anglais', 'Arab Anglais',
    'Bilingual Services Portal', 'بوابة خدمات ثنائية اللغة',
    'A service platform for clients.', 'منصة لتقديم الخدمات للعملاء.',
    'Arabic English learning platform Supabase', 'منصة تعلم عربي إنجليزي Supabase',
    'Arab Anglais E-Learning Platform | El Hussainy', 'منصة التعلم الإلكتروني Arab Anglais | الحسيني',
    'Interactive language LMS with Supabase real-time quiz scoring, spaced-repetition vocabulary engine, and Framer Motion gamified progress.', 'LMS لغة تفاعلي مع Supabase لتسجيل نقاط اختبارات فورية ومحرك مفردات التكرار المتباعد وتقدم ممتع بـ Framer Motion.',
    '["Next.js","Tailwind CSS"]'::jsonb, '["Services","React","Dashboard"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project4/cover.jpg","alt":"Arab Anglais LMS"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A service platform for clients.', 'منصة لتقديم الخدمات للعملاء.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • Tailwind CSS', 'Next.js • Tailwind CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    14, 'noda-ai-tool', 'published', false,
    'Noda AI Tool', 'أداة Noda AI',
    'Code Generation AI Assistant', 'مساعد ذكاء اصطناعي لتوليد الأكواد',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'AI content generator SSE streaming', 'مولّد محتوى AI SSE بث فوري',
    'Noda AI | Intelligent Code Generation Tool', 'Noda AI | منصة توليد الأكواد بالذكاء الاصطناعي',
    'A powerful AI tool that generates software code using Ollama, Groq, and OpenAI, built for rapid component and UI generation.', 'أداة ذكاء اصطناعي قوية لتوليد الأكواد البرمجية باستخدام نماذج Ollama و Groq و OpenAI، مصممة لتسريع عملية التطوير.',
    '["Next.js","OpenAI API","Groq","Ollama"]'::jsonb, '["AI","LLM","Tooling"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Noda AI"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Next.js • OpenAI API • Groq • Ollama', 'Next.js • OpenAI API • Groq • Ollama',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    15, 'restaurant-specialized-saas', 'published', false,
    'Restaurant QR Menu SaaS', 'نظام قائمة QR للمطاعم SaaS',
    'One QR code per table. One price update in the dashboard. Every customer''s phone updates instantly — no reprint, ever.', 'رمز QR واحد لكل طاولة. تحديث سعر واحد في لوحة التحكم. هاتف كل عميل يتحدث فوريًا — بدون إعادة طباعة، أبدًا.',
    'A system similar to Ahwa but specialized for restaurant management.', 'نظام مشابه لقهوة ولكنه مخصص أكثر لإدارة المطاعم.',
    'QR menu SaaS restaurant system', 'نظام قائمة QR SaaS للمطاعم',
    'Restaurant QR Menu SaaS | El Hussainy', 'نظام قائمة QR للمطاعم SaaS | الحسيني',
    'Multi-tenant restaurant QR menu system with instant price updates, allergen management, and branch-level menu isolation.', 'نظام قائمة QR متعدد المستأجرين للمطاعم مع تحديثات فورية للأسعار وإدارة الحساسيات وعزل القوائم على مستوى الفرع.',
    '["Next.js","PostgreSQL","Supabase"]'::jsonb, '["SaaS","F&B","QR"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project2/cover.jpg","alt":"QR Menu System"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A system similar to Ahwa but specialized for restaurant management.', 'نظام مشابه لقهوة ولكنه مخصص أكثر لإدارة المطاعم.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • PostgreSQL • Supabase', 'Next.js • PostgreSQL • Supabase',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    16, 'kenz-ecommerce', 'published', false,
    'Kenz Ecommerce', 'متجر كنز',
    'Zero dropped transactions: engineered Tabby, Tamara, and Moyasar BNPL flows with server-side webhook verification.', 'صفر معاملات مفقودة: هندسة تدفقات Tabby وTamara وMoyasar BNPL مع التحقق من webhook من جانب الخادم.',
    'A React project with a single dashboard. Full e-commerce system (not SaaS) for a single vendor with multiple products, including ERP, CRM, inventory tracking, and accounting.', 'مشروع React بلوحة تحكم واحدة. نظام متجر إلكتروني متكامل (ليس SaaS) لمتجر واحد متعدد المنتجات يشمل ERP و CRM وتتبع للمخزون والفواتير المحاسبية.',
    'Tabby Tamara Moyasar payment integration Next.js', 'دمج Tabby Tamara Moyasar للدفع Next.js',
    'Kenz Ecommerce — Gulf Payment Integration | El Hussainy', 'متجر كنز — دمج الدفع الخليجي | الحسيني',
    'Next.js e-commerce with Tabby, Tamara BNPL and Moyasar payment integration, server-side webhook verification, and zero transaction failure rate.', 'تجارة إلكترونية Next.js مع دمج Tabby وTamara BNPL وMoyasar، والتحقق من webhook من جانب الخادم، ومعدل فشل معاملات صفر.',
    '["React","Node.js","PostgreSQL"]'::jsonb, '["E-Commerce","FinTech","Payments"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project4/cover.jpg","alt":"Kenz Store"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A React project with a single dashboard. Full e-commerce system (not SaaS) for a single vendor with multiple products, including ERP, CRM, inventory tracking, and accounting.', 'مشروع React بلوحة تحكم واحدة. نظام متجر إلكتروني متكامل (ليس SaaS) لمتجر واحد متعدد المنتجات يشمل ERP و CRM وتتبع للمخزون والفواتير المحاسبية.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'React • Node.js • PostgreSQL', 'React • Node.js • PostgreSQL',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    17, 'holospace-simulator', 'published', false,
    'Holospace', 'Holospace',
    'Web-Based Desktop Simulator', 'محاكي سطح مكتب يعمل على الويب',
    'A web simulation of desktop applications (like winapp) online.', 'نظام محاكاة ويب لتطبيقات سطح المكتب (مثل winapp) عبر الإنترنت.',
    'WebGL 3D room configurator React Three Fiber', 'مُهيّئ غرف ثلاثي الأبعاد WebGL React Three Fiber',
    'Holospace 3D VR Room Configurator | El Hussainy', 'مُهيّئ غرف VR ثلاثي الأبعاد Holospace | الحسيني',
    'Browser-native WebGL 3D room configurator for VR hardware with React Three Fiber, drag-drop nodes, and spatial collision detection.', 'مُهيّئ غرف ثلاثي الأبعاد WebGL في المتصفح لأجهزة VR مع React Three Fiber وعقد سحب وإفلات وكشف تصادم مكاني.',
    '["React","CSS Modules"]'::jsonb, '["Simulator","WebGL","Three.js","3D"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project5/cover.jpg","alt":"Holospace 3D"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A web simulation of desktop applications (like winapp) online.', 'نظام محاكاة ويب لتطبيقات سطح المكتب (مثل winapp) عبر الإنترنت.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'React • CSS Modules', 'React • CSS Modules',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    18, 'multiverse-showcase', 'published', false,
    'Multiverse Showcase', 'Multiverse Showcase',
    'Cinematic 3D Portfolio', 'ملف شخصي سينمائي ثلاثي الأبعاد',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'HTML5 Canvas interactive galaxy map', 'خريطة مجرة تفاعلية HTML5 Canvas',
    'Multiverse Showcase — Canvas Galaxy Map | El Hussainy', 'عرض الأكوان — خريطة مجرة Canvas | الحسيني',
    'Custom HTML5 Canvas infinite galaxy map with trigonometric star plotting, pan/zoom controls, and node relationship graph navigation.', 'خريطة مجرة Canvas HTML5 مخصصة لا نهائية مع رسم نجوم مثلثي وضوابط تحريك/تكبير وتنقل بين رسوم علاقات العقد.',
    '["React","WebGL","Cinematic Animations"]'::jsonb, '["Portfolio","3D","Cinematic"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project6/cover.jpg","alt":"Multiverse Map"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'React • WebGL • Cinematic Animations', 'React • WebGL • Cinematic Animations',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    19, 'pulsereach-astra-child', 'published', false,
    'Pulsereach Marketing', 'Pulsereach للتسويق',
    'Custom WordPress Agency Site', 'موقع وكالة WordPress مخصص',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'WordPress React hybrid Astra child theme', 'WordPress React هجين قالب Astra فرعي',
    'Pulsereach Hybrid WordPress React Site | El Hussainy', 'موقع Pulsereach الهجين WordPress React | الحسيني',
    'Custom Astra Child Theme with Webpack pipeline injecting React components into WordPress shortcodes for hybrid CMS architecture.', 'قالب Astra فرعي مخصص مع مسار Webpack يحقن مكونات React في WordPress shortcodes لمعمارية CMS هجينة.',
    '["WordPress","Astra Child Theme","PHP","CSS"]'::jsonb, '["Digital Marketing","WordPress","Agency"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project7/cover.jpg","alt":"Pulsereach"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'WordPress • Astra Child Theme • PHP • CSS', 'WordPress • Astra Child Theme • PHP • CSS',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    20, 'nori-restaurant-ui', 'published', false,
    'Nori Sushi UI', 'واجهة Nori Sushi',
    'Static Frontend Excellence', 'تفوق الواجهة الثابتة',
    'A separate static frontend project for a restaurant.', 'مشروع منفصل لواجهة أمامية (Static) لمطعم.',
    'luxury restaurant UI glassmorphism', 'واجهة مطعم فاخرة glassmorphism',
    'Nori Restaurant UI — Luxury Design | El Hussainy', 'واجهة نوري للمطعم — تصميم فاخر | الحسيني',
    'Premium restaurant landing page with glassmorphism design, parallax food photography, micro-animations, and online table reservation.', 'صفحة هبوط مطعم فاخرة مع تصميم glassmorphism وتصوير طعام parallax ورسوم دقيقة وحجز طاولات عبر الإنترنت.',
    '["HTML","CSS","JavaScript"]'::jsonb, '["UI","Frontend","Restaurant"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Nori Sushi UI"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A separate static frontend project for a restaurant.', 'مشروع منفصل لواجهة أمامية (Static) لمطعم.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'HTML • CSS • JavaScript', 'HTML • CSS • JavaScript',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    21, 'crm-system-python', 'published', false,
    'Python Odoo-Clone CRM', 'نظام CRM شبيه بـ Odoo مبني بـ Python',
    'Dockerized Python CRM', 'CRM Python مع Docker',
    'A CRM simulation of Odoo 17 built with Python and Docker, including WhatsApp automation and full CRM features.', 'نظام CRM محاكاة لـ Odoo 17 مبني على بايثون و Docker مع أتمتة واتساب وكافة ميزات إدارة العملاء.',
    'Python FastAPI CRM data pipeline', 'مسار بيانات Python FastAPI CRM',
    'Python Enterprise CRM | El Hussainy', 'CRM المؤسسي بـ Python | الحسيني',
    'Enterprise CRM backend with FastAPI and Pandas data ingestion pipeline, CSV sanitisation, deduplication, and RESTful query API.', 'خادم CRM مؤسسي مع مسار استيعاب بيانات FastAPI و Pandas وتنظيف CSV وإزالة التكرار وواجهة API استعلام RESTful.',
    '["Python","Docker","PostgreSQL"]'::jsonb, '["CRM","Python","Docker"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project2/cover.jpg","alt":"Python CRM"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A CRM simulation of Odoo 17 built with Python and Docker, including WhatsApp automation and full CRM features.', 'نظام CRM محاكاة لـ Odoo 17 مبني على بايثون و Docker مع أتمتة واتساب وكافة ميزات إدارة العملاء.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Python • Docker • PostgreSQL', 'Python • Docker • PostgreSQL',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    22, 'animation-studio-system', 'published', false,
    'Animation Studio Manager', 'مدير استوديو الرسوم المتحركة',
    'Team & Asset Management Platform', 'منصة إدارة الفريق والأصول',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'secure video review portal AWS S3', 'بوابة مراجعة فيديو آمنة AWS S3',
    'Animation Studio Video Review Portal | El Hussainy', 'بوابة مراجعة فيديو استوديو الرسوم | الحسيني',
    'Secure animation draft review portal with AWS S3 signed URLs, timestamped client annotations, and frame-accurate feedback system.', 'بوابة مراجعة مسودات رسوم آمنة مع AWS S3 signed URLs وتعليقات عملاء بطابع زمني ونظام تغذية راجعة دقيق الإطارات.',
    '["Asset Management","CSS Generator","Workflow"]'::jsonb, '["Management","Animation","Tooling"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project3/cover.jpg","alt":"Animation Studio"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Asset Management • CSS Generator • Workflow', 'Asset Management • CSS Generator • Workflow',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    23, 'arab-tourism', 'published', false,
    'Arab Tourism Portal', 'بوابة السياحة العربية',
    'Tourism Directory Interface', 'واجهة دليل سياحي',
    'Frontend interface for a tourist guide only.', 'واجهة أمامية لدليل سياحي فقط.',
    'tourism CRM visa tracking SMS notifications', 'CRM سياحة تتبع تأشيرة إشعارات SMS',
    'Arab Tourism Visa CRM Portal | El Hussainy', 'بوابة CRM التأشيرات السياحية | الحسيني',
    'Tourism agency CRM with visa status milestone tracking and automated SMS traveler notifications, reducing support calls by 80%.', 'CRM وكالة سياحة مع تتبع معالم حالة التأشيرة وإشعارات SMS تلقائية للمسافرين، تخفّض مكالمات الدعم 80%.',
    '["Next.js","Tailwind CSS"]'::jsonb, '["Tourism","Frontend","UI"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project4/cover.jpg","alt":"Arab Tourism Portal"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'Frontend interface for a tourist guide only.', 'واجهة أمامية لدليل سياحي فقط.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • Tailwind CSS', 'Next.js • Tailwind CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    24, 'real-estate-ui', 'published', false,
    'Real Estate Explorer UI', 'واجهة مستكشف العقارات',
    'Experimental Frontend Concept', 'فكرة واجهة أمامية تجريبية',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'real estate geospatial filter React', 'تصفية جغرافية عقارية React',
    'Real Estate Property Search UI | El Hussainy', 'واجهة بحث العقارات | الحسيني',
    'Real estate search React app with client-side geospatial filtering, instant bounding-box spatial queries, and map-synced property listings.', 'تطبيق بحث عقاري React مع تصفية جغرافية مكانية من جانب العميل واستعلامات bounding-box فورية وقوائم عقارات متزامنة مع الخريطة.',
    '["React","UI/UX","Framer Motion"]'::jsonb, '["Frontend","UI","Showcase"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project3/cover.jpg","alt":"Real Estate Explorer"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'React • UI/UX • Framer Motion', 'React • UI/UX • Framer Motion',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    25, 'gedo-store', 'published', false,
    'Custom PHP E-Commerce (Noda, Gedo, Rose)', 'متجر إلكتروني مخصص بـ PHP (Noda, Gedo, Rose)',
    'PHP/MySQL Multi-Tenant E-Commerce', 'تجارة إلكترونية متعددة المستأجرين باستخدام PHP/MySQL',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'WooCommerce POS inventory sync plugin', 'إضافة مزامنة مخزون WooCommerce POS',
    'Gedo Store — WooCommerce POS Sync | El Hussainy', 'متجر جدو — مزامنة WooCommerce POS | الحسيني',
    'Custom WordPress plugin for real-time bidirectional inventory sync between physical POS and WooCommerce, eliminating overselling.', 'إضافة WordPress مخصصة لمزامنة مخزون ثنائية الاتجاه بالوقت الحقيقي بين POS والفعلي وWooCommerce، تُلغي البيع الزائد.',
    '["PHP","MySQL","HTML","CSS"]'::jsonb, '["E-Commerce","PHP","Dashboard"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project2/cover.jpg","alt":"Gedo Store"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'PHP • MySQL • HTML • CSS', 'PHP • MySQL • HTML • CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    26, 'dashboard-admin-ui', 'published', false,
    'Dashboard Admin UI Toolkit', 'مجموعة أدوات واجهة الأدمن',
    'An Atomic Design React component library with Framer Motion — dark mode, complex data tables, and a sidebar navigation system that reduced internal tool dev time by 70%.', 'مكتبة مكونات React بالتصميم الذري مع Framer Motion — وضع مظلم وجداول بيانات معقدة ونظام تنقل جانبي قلّص وقت تطوير الأدوات الداخلية 70%.',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'React admin dashboard component library Framer Motion', 'مكتبة مكونات لوحة أدمن React Framer Motion',
    'Admin Dashboard UI Toolkit | El Hussainy', 'مجموعة أدوات واجهة لوحة الأدمن | الحسيني',
    'Atomic Design React admin component library with Framer Motion, dark mode, complex data tables, and animated sidebar navigation.', 'مكتبة مكونات أدمن React بالتصميم الذري مع Framer Motion ووضع مظلم وجداول بيانات معقدة وتنقل جانبي متحرك.',
    '["React","Framer Motion","Tailwind CSS","Atomic Design"]'::jsonb, '["UI Kit","Dashboard","Design System"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project2/cover.jpg","alt":"Admin UI Kit"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'React • Framer Motion • Tailwind CSS • Atomic Design', 'React • Framer Motion • Tailwind CSS • Atomic Design',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    27, 'lamar-ecommerce', 'published', false,
    'Lamar E-Commerce', 'Lamar للتجارة الإلكترونية',
    'Custom Fullstack E-Commerce', 'متجر إلكتروني مخصص بالكامل',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'Next.js i18n Edge Middleware international ecommerce', 'Next.js i18n Edge Middleware تجارة دولية',
    'Lamar International Store — Next.js i18n | El Hussainy', 'متجر لمار الدولي — Next.js i18n | الحسيني',
    'International Next.js e-commerce with Edge Middleware locale routing, live currency conversion, and per-country shipping rules.', 'تجارة إلكترونية دولية Next.js مع توجيه locale بـ Edge Middleware وتحويل عملة حي وقواعد شحن لكل دولة.',
    '["Fullstack","Custom DB","Dashboard"]'::jsonb, '["E-Commerce","Fullstack","Custom"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project7/cover.jpg","alt":"Lamar Store"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Fullstack • Custom DB • Dashboard', 'Fullstack • Custom DB • Dashboard',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    28, 'alkhair-store', 'published', false,
    'Al Khair React Store & POS', 'متجر الخير React & POS',
    'Omnichannel React E-Commerce', 'تجارة إلكترونية Omnichannel',
    'A React project with a single dashboard and an internal POS system linking offline and online sales.', 'مشروع React بلوحة تحكم واحدة مع نظام نقطة بيع (POS) داخلية للمحل لربط المبيعات الأوفلاين والأونلاين.',
    'WooCommerce B2B wholesale bulk order', 'WooCommerce B2B جملة طلب جماعي',
    'Al Khair B2B Wholesale WooCommerce | El Hussainy', 'متجر الخير B2B جملة WooCommerce | الحسيني',
    'B2B wholesale WooCommerce with bulk order matrix UI, dynamic server-side volume discounts, and business-specific checkout flows.', 'WooCommerce B2B جملة مع واجهة مصفوفة طلبات جماعية وخصومات حجم ديناميكية من جانب الخادم وتدفقات دفع خاصة بالأعمال.',
    '["React","Node.js","PostgreSQL"]'::jsonb, '["E-Commerce","React","POS"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project5/cover.jpg","alt":"Al Khair B2B"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A React project with a single dashboard and an internal POS system linking offline and online sales.', 'مشروع React بلوحة تحكم واحدة مع نظام نقطة بيع (POS) داخلية للمحل لربط المبيعات الأوفلاين والأونلاين.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'React • Node.js • PostgreSQL', 'React • Node.js • PostgreSQL',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    29, 'noda-clothing-brand', 'published', false,
    'Custom PHP E-Commerce (Noda, Gedo, Rose)', 'متجر إلكتروني مخصص (Noda, Gedo, Rose)',
    'PHP/MySQL Multi-Tenant E-Commerce', 'تجارة إلكترونية متعددة المستأجرين باستخدام PHP/MySQL',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'fashion storefront Shopify Framer Motion', 'متجر أزياء Shopify Framer Motion',
    'Noda Clothing — Fashion Storefront | El Hussainy', 'ملابس نودا — واجهة متجر أزياء | الحسيني',
    'Editorial fashion e-commerce with Shopify Storefront API, Framer Motion scroll parallax, and immersive full-screen product discovery.', 'تجارة إلكترونية أزياء تحريرية مع Shopify Storefront API وFramer Motion scroll parallax واكتشاف منتجات غامر بشاشة كاملة.',
    '["PHP","MySQL","HTML","CSS"]'::jsonb, '["E-Commerce","PHP","Dashboard"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project3/cover.jpg","alt":"Noda Clothing"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A single dashboard (Rebrand) built with PHP and MySQL for an e-commerce store.', 'لوحة تحكم واحدة (Rebrand) مبنية بتقنيات PHP و MySQL لمتجر إلكتروني.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'PHP • MySQL • HTML • CSS', 'PHP • MySQL • HTML • CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    30, 'saqi-sa-seo', 'published', false,
    'Saqi SA SEO', 'Saqi SA SEO',
    'Technical Schema & GTM Optimization', 'تحسين المخططات التقنية وGTM',
    'A challenge similar to the Ramz platform, integrated and indexed via Google Tag Manager.', 'تحدي مشابه لمنصة رمز، تم الربط وحقن الفهرسة عبر Google Tag Manager.',
    'Arabic programmatic SEO Saudi Arabia', 'SEO عربي برمجي السعودية',
    'Saqi.sa Programmatic SEO | El Hussainy', 'SEO برمجي Saqi.sa | الحسيني',
    'Arabic programmatic SEO for Saudi water delivery: hyper-localised landing pages per neighbourhood with NLP intent matching, driving 50K monthly organic visitors.', 'SEO عربي برمجي لتوصيل مياه سعودي: صفحات هبوط محلية للغاية لكل حي مع مطابقة نية NLP، تجلب 50K زائر عضوي شهريًا.',
    '["Google Tag Manager","SEO"]'::jsonb, '["SEO","GTM","Schema"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project7/cover.jpg","alt":"Saqi SEO"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A challenge similar to the Ramz platform, integrated and indexed via Google Tag Manager.', 'تحدي مشابه لمنصة رمز، تم الربط وحقن الفهرسة عبر Google Tag Manager.',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Google Tag Manager • SEO', 'Google Tag Manager • SEO',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    31, 'vortexq8-seo', 'published', false,
    'Vortexq8', 'Vortexq8',
    'Custom JS SEO Injection', 'حقن SEO مخصص بلغة JavaScript',
    'Completely redesigned using Custom CSS and JS, injecting Google indexing into the Ramz platform which restricts HTML edits.', 'تغيير التصميم بالكامل بـ Custom CSS و Custom JS، مع حقن فهرسة جوجل في منصة رمز (التي لا تقبل تعديل HTML).',
    'Google Core Update penalty recovery SEO', 'استعادة عقوبة Google Core Update SEO',
    'Vortexq8 Google Penalty Recovery | El Hussainy', 'استعادة عقوبة جوجل Vortexq8 | الحسيني',
    'Google Core Update penalty recovery: toxic link disavow, Next.js performance rebuild, structured data injection, and top-3 ranking restoration.', 'استعادة عقوبة Google Core Update: تنصّل روابط سامة وإعادة بناء أداء Next.js وحقن بيانات منظمة واستعادة تصنيفات أعلى 3.',
    '["Custom CSS","Custom JS","SEO"]'::jsonb, '["SEO","Redesign","JavaScript"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project6/cover.jpg","alt":"Vortexq8 Analytics"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'Completely redesigned using Custom CSS and JS, injecting Google indexing into the Ramz platform which restricts HTML edits.', 'تغيير التصميم بالكامل بـ Custom CSS و Custom JS، مع حقن فهرسة جوجل في منصة رمز (التي لا تقبل تعديل HTML).',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Custom CSS • Custom JS • SEO', 'Custom CSS • Custom JS • SEO',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    32, 'store-static-ui', 'published', false,
    'Store Static UI', 'واجهة متجر ثابتة',
    'E-Commerce Frontend Showcase', 'عرض واجهة تجارة إلكترونية',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'Next.js SSG product catalogue GitHub Pages', 'كتالوج منتجات Next.js SSG GitHub Pages',
    'Static Product Catalogue — Next.js Jamstack | El Hussainy', 'كتالوج المنتجات الثابت — Next.js Jamstack | الحسيني',
    'Zero-cost Jamstack product catalogue built with Next.js SSG, GitHub Pages hosting, and GitHub Actions CI/CD deployment.', 'كتالوج منتجات Jamstack بتكلفة صفر مبني بـ Next.js SSG واستضافة GitHub Pages ونشر GitHub Actions CI/CD.',
    '["HTML","CSS","JS","UI/UX"]'::jsonb, '["Frontend","UI","Showcase"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project4/cover.jpg","alt":"Static Store"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'HTML • CSS • JS • UI/UX', 'HTML • CSS • JS • UI/UX',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    33, 'monera-platform', 'published', false,
    'Monera Platform', 'منصة Monera',
    'Completed Undelivered Project', 'مشروع مكتمل غير مُسلَّم',
    'Project successfully developed and implemented.', 'مشروع تم برمجته وتنفيذه بنجاح.',
    'service management platform React', 'منصة إدارة خدمات React',
    'Monera Service Platform | El Hussainy', 'منصة منيرة للخدمات | الحسيني',
    'Full-featured service management React platform with Framer Motion animations and premium user experience.', 'منصة إدارة خدمات React كاملة المزايا مع رسوم Framer Motion وتجربة مستخدم راقية.',
    '["Web Platform","Frontend","Backend"]'::jsonb, '["Web App","Portfolio"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project5/cover.jpg","alt":"Monera"}]'::jsonb,
    'Requirement & Execution', 'الطلب والتنفيذ',
    'Requirements implemented programmatically.', 'تم تنفيذ المطلوب برمجياً.',
    'Project completed and delivered.', 'اكتمال المشروع والتسليم.',
    'Development', 'تطوير',
    'Web Platform • Frontend • Backend', 'Web Platform • Frontend • Backend',
    '[]'::jsonb, '[]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );
INSERT INTO projects (
    universe, slug, status, featured, 
    name_en, name_ar, tagline_en, tagline_ar, description_en, description_ar,
    focus_keyword_en, focus_keyword_ar, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar,
    tech_stack, tags, repo_url, live_url, screens,
    case_study_problem_en, case_study_problem_ar, case_study_solution_en, case_study_solution_ar,
    case_study_outcome_en, case_study_outcome_ar, case_study_role_en, case_study_role_ar,
    case_study_stack_en, case_study_stack_ar, case_study_steps_en, case_study_steps_ar,
    faqs,
    highlight_key_points_en, highlight_key_points_ar, highlight_focus_en, highlight_focus_ar,
    highlight_role_en, highlight_role_ar
  ) VALUES (
    36, 'crm-system-nextjs', 'published', false,
    'Next.js CRM Ecosystem', 'نظام CRM مبني على Next.js',
    'Automated CRM with WhatsApp Integration', 'CRM آلي مع تكامل واتساب',
    'A complete CRM system for companies built with Next.js, featuring WhatsApp automation, agenda, and deals management.', 'نظام CRM كامل للشركات مبني بـ Next.js يحتوي على أتمتة بالواتساب، أجندة، وإدارة الصفقات (Deals).',
    'Cloudflare Workers CRM edge computing', 'CRM Cloudflare Workers حوسبة طرفية',
    'Edge CRM — Cloudflare Workers | El Hussainy', 'CRM الطرفي — Cloudflare Workers | الحسيني',
    'Cloudflare Workers-powered CRM with edge-computed API routes delivering 90% latency reduction for distributed global sales teams.', 'CRM مدعوم بـ Cloudflare Workers مع مسارات API محسوبة على الحافة تقدّم تقليص وقت استجابة 90% للفرق مبيعات عالمية موزعة.',
    '["Next.js","WhatsApp API","Tailwind CSS"]'::jsonb, '["CRM","Next.js","Automation"]'::jsonb, '', '',
    '[{"id":"s1","src":"/assets/project1/cover.jpg","alt":"Edge CRM"}]'::jsonb,
    'Software development and implementation', 'التطوير البرمجي والتنفيذ',
    'A complete CRM system for companies built with Next.js, featuring WhatsApp automation, agenda, and deals management.', 'نظام CRM كامل للشركات مبني بـ Next.js يحتوي على أتمتة بالواتساب، أجندة، وإدارة الصفقات (Deals).',
    'Project successfully built and developed', 'تم بناء المشروع وتطويره بنجاح',
    'Developer', 'مطور',
    'Next.js • WhatsApp API • Tailwind CSS', 'Next.js • WhatsApp API • Tailwind CSS',
    '["Analysis","Execution"]'::jsonb, '["التحليل","التنفيذ"]'::jsonb,
    '[]'::jsonb,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL
  );

-- BLOG POSTS
DELETE FROM blog_posts;
INSERT INTO blog_posts (
    slug, status, title_en, title_ar, summary_en, summary_ar, content_en, content_ar, tags, cover_image, published_date
  ) VALUES (
    'rescuing-failing-platform-multi-tenant', 'published',
    'How I Rescued a Failing Media Platform and Converted It to Multi-Tenant', 'كيف قمت بإنقاذ منصة ميديا متعثرة وتحويلها إلى نظام Multi-Tenant',
    'A deep dive into fixing the ''black screen of death'', dramatically improving load times, and building a missing admin dashboard from scratch.', 'رحلة تقنية في إنقاذ مشروع متعثر: من حل مشكلة الشاشة السوداء وبطء التصفح إلى بناء لوحة تحكم وإعداد تعدد المستأجرين.',
    '[{"type":"p","text":{"en":"I recently took over a failing project (Lakatat) that was suffering from severe performance issues. The client was experiencing a ''black screen'' on load, extremely slow navigation, and shockingly, the platform had absolutely no admin control panel.","ar":"مؤخراً استلمت مشروع منصة (لقطات) وهو في حالة انهيار تقني. العميل كان يواجه ''شاشة سوداء'' عند التحميل، وبطء شديد في التصفح، والمفاجأة أن النظام لم يكن يحتوي على أي لوحة تحكم للإدارة."}},{"type":"h2","text":{"en":"Step 1: Diagnosing the Black Screen & Speed Issues","ar":"الخطوة الأولى: تشخيص الشاشة السوداء ومشاكل السرعة"}},{"type":"p","text":{"en":"The first priority was stopping the bleeding. The black screen was caused by unhandled client-side exceptions during hydration and massive, unoptimized API payloads blocking the main thread. I rewrote the fetching logic to use proper server-side rendering (SSR) and implemented pagination for the video feeds. The difference was night and day.","ar":"الأولوية الأولى كانت إيقاف النزيف. الشاشة السوداء كانت بسبب أخطاء غير معالجة في الواجهة (Client-side) وحمولات بيانات ضخمة تعطل المتصفح. قمت بإعادة كتابة منطق جلب البيانات ليعتمد على الخادم (SSR)، وطبقت نظام الترقيم (Pagination) للفيديوهات. النتيجة كانت فورية."}},{"type":"h2","text":{"en":"Step 2: Building the Missing Admin & Multi-Tenant Architecture","ar":"الخطوة الثانية: بناء لوحة التحكم المفقودة وبنية Multi-Tenant"}},{"type":"p","text":{"en":"A platform without an admin panel is a ticking time bomb. I developed a comprehensive dynamic dashboard allowing complete control over videos, playlists, stories, and the footer content. Moreover, I overhauled the database schema to support multi-tenant user roles, ensuring secure and isolated environments for different types of users and content creators.","ar":"أي منصة بدون لوحة تحكم هي قنبلة موقوتة. قمت ببرمجة لوحة تحكم ديناميكية شاملة تتيح التحكم بالفيديوهات، القصص، السلاسل، وحتى فوتر الموقع. الأهم من ذلك، أعدت هندسة قاعدة البيانات لتدعم تعدد المستأجرين (Multi-tenant)، مما وفر بيئة آمنة ومعزولة لصناع المحتوى."}},{"type":"p","text":{"en":"Finally, I integrated Google AdSense indexing APIs and designated ad spaces. The project went from a broken, unusable state to a fast, profitable, and highly manageable platform.","ar":"أخيراً، قمت بربط واجهات فهرسة Google AdSense وتخصيص مساحات إعلانية. تحول المشروع من حالة الفشل التام إلى منصة سريعة، مربحة، وسهلة الإدارة تماماً."}}]'::jsonb, '[{"type":"p","text":{"en":"I recently took over a failing project (Lakatat) that was suffering from severe performance issues. The client was experiencing a ''black screen'' on load, extremely slow navigation, and shockingly, the platform had absolutely no admin control panel.","ar":"مؤخراً استلمت مشروع منصة (لقطات) وهو في حالة انهيار تقني. العميل كان يواجه ''شاشة سوداء'' عند التحميل، وبطء شديد في التصفح، والمفاجأة أن النظام لم يكن يحتوي على أي لوحة تحكم للإدارة."}},{"type":"h2","text":{"en":"Step 1: Diagnosing the Black Screen & Speed Issues","ar":"الخطوة الأولى: تشخيص الشاشة السوداء ومشاكل السرعة"}},{"type":"p","text":{"en":"The first priority was stopping the bleeding. The black screen was caused by unhandled client-side exceptions during hydration and massive, unoptimized API payloads blocking the main thread. I rewrote the fetching logic to use proper server-side rendering (SSR) and implemented pagination for the video feeds. The difference was night and day.","ar":"الأولوية الأولى كانت إيقاف النزيف. الشاشة السوداء كانت بسبب أخطاء غير معالجة في الواجهة (Client-side) وحمولات بيانات ضخمة تعطل المتصفح. قمت بإعادة كتابة منطق جلب البيانات ليعتمد على الخادم (SSR)، وطبقت نظام الترقيم (Pagination) للفيديوهات. النتيجة كانت فورية."}},{"type":"h2","text":{"en":"Step 2: Building the Missing Admin & Multi-Tenant Architecture","ar":"الخطوة الثانية: بناء لوحة التحكم المفقودة وبنية Multi-Tenant"}},{"type":"p","text":{"en":"A platform without an admin panel is a ticking time bomb. I developed a comprehensive dynamic dashboard allowing complete control over videos, playlists, stories, and the footer content. Moreover, I overhauled the database schema to support multi-tenant user roles, ensuring secure and isolated environments for different types of users and content creators.","ar":"أي منصة بدون لوحة تحكم هي قنبلة موقوتة. قمت ببرمجة لوحة تحكم ديناميكية شاملة تتيح التحكم بالفيديوهات، القصص، السلاسل، وحتى فوتر الموقع. الأهم من ذلك، أعدت هندسة قاعدة البيانات لتدعم تعدد المستأجرين (Multi-tenant)، مما وفر بيئة آمنة ومعزولة لصناع المحتوى."}},{"type":"p","text":{"en":"Finally, I integrated Google AdSense indexing APIs and designated ad spaces. The project went from a broken, unusable state to a fast, profitable, and highly manageable platform.","ar":"أخيراً، قمت بربط واجهات فهرسة Google AdSense وتخصيص مساحات إعلانية. تحول المشروع من حالة الفشل التام إلى منصة سريعة، مربحة، وسهلة الإدارة تماماً."}}]'::jsonb,
    '["Next.js","Performance","Architecture","Multi-tenant"]'::jsonb, NULL, '2024-03-15T10:00:00Z'
  );
INSERT INTO blog_posts (
    slug, status, title_en, title_ar, summary_en, summary_ar, content_en, content_ar, tags, cover_image, published_date
  ) VALUES (
    'building-ahwa-saas-operating-system', 'published',
    'Building Ahwa: A SaaS Operating System for Coffee Shops', 'بناء نظام ''قهوة'': منصة SaaS ونظام تشغيل متكامل للمقاهي',
    'How I engineered a complete SaaS ecosystem encompassing POS, inventory, and analytics from scratch using Next.js.', 'كيف قمت بهندسة بيئة SaaS متكاملة تشمل نقاط البيع (POS)، المخزون، والتحليلات من الصفر باستخدام Next.js.',
    '[{"type":"p","text":{"en":"When I started developing ''Ahwa'', the goal wasn''t just to build another Point of Sale (POS) software. I wanted to build an entire Operating System (OS) for coffee shops and restaurants—a single unified platform handling everything from the cashier''s screen to backend inventory and staff management.","ar":"عندما بدأت في تطوير مشروع ''قهوة'' (Ahwa)، لم يكن الهدف مجرد بناء برنامج نقاط بيع (POS) آخر. أردت بناء نظام تشغيل (OS) متكامل للمقاهي والمطاعم؛ منصة واحدة موحدة تدير كل شيء من شاشة الكاشير إلى جرد المخزون في الخلفية وإدارة الموظفين."}},{"type":"h2","text":{"en":"The Complexity of Real-Time Inventory","ar":"تعقيدات جرد المخزون اللحظي"}},{"type":"p","text":{"en":"One of the biggest challenges in a restaurant SaaS is inventory mapping. When a cashier sells a ''Latte'', the system needs to dynamically deduct 15g of coffee beans, 200ml of milk, and 1 paper cup in real-time. Designing a relational database schema in PostgreSQL that maps final products to raw ingredients without causing massive performance bottlenecks during peak hours required meticulous query optimization.","ar":"أحد أكبر التحديات في أنظمة SaaS للمطاعم هو ربط المبيعات بالمخزون. عندما يبيع الكاشير ''لاتيه''، يجب أن يخصم النظام 15 جراماً من القهوة، و200 مل من الحليب، وكوباً ورقياً واحداً في نفس اللحظة. هندسة قاعدة بيانات (PostgreSQL) تربط المنتجات النهائية بالمواد الخام دون التسبب باختناقات في الأداء وقت الذروة تطلب تحسيناً دقيقاً للاستعلامات."}},{"type":"h2","text":{"en":"Offline-First and Reliability","ar":"دعم العمل بدون إنترنت والموثوقية"}},{"type":"p","text":{"en":"Coffee shops can''t stop operating if the internet goes down. Leveraging modern web capabilities, I ensured the core POS functionalities remained active offline, syncing seamlessly with the server once the connection is restored. This robust architecture is what makes Ahwa a true OS for the F&B industry.","ar":"لا يمكن للمقهى أن يتوقف عن العمل إذا انقطع الإنترنت. باستخدام التقنيات الحديثة للويب، ضمنت أن تظل الوظائف الأساسية للكاشير تعمل بدون إنترنت (Offline)، ليتم مزامنة البيانات بسلاسة مع السيرفر بمجرد عودة الاتصال. هذه البنية التحتية القوية هي ما يجعل Ahwa نظام تشغيل حقيقي لقطاع الأغذية والمشروبات."}}]'::jsonb, '[{"type":"p","text":{"en":"When I started developing ''Ahwa'', the goal wasn''t just to build another Point of Sale (POS) software. I wanted to build an entire Operating System (OS) for coffee shops and restaurants—a single unified platform handling everything from the cashier''s screen to backend inventory and staff management.","ar":"عندما بدأت في تطوير مشروع ''قهوة'' (Ahwa)، لم يكن الهدف مجرد بناء برنامج نقاط بيع (POS) آخر. أردت بناء نظام تشغيل (OS) متكامل للمقاهي والمطاعم؛ منصة واحدة موحدة تدير كل شيء من شاشة الكاشير إلى جرد المخزون في الخلفية وإدارة الموظفين."}},{"type":"h2","text":{"en":"The Complexity of Real-Time Inventory","ar":"تعقيدات جرد المخزون اللحظي"}},{"type":"p","text":{"en":"One of the biggest challenges in a restaurant SaaS is inventory mapping. When a cashier sells a ''Latte'', the system needs to dynamically deduct 15g of coffee beans, 200ml of milk, and 1 paper cup in real-time. Designing a relational database schema in PostgreSQL that maps final products to raw ingredients without causing massive performance bottlenecks during peak hours required meticulous query optimization.","ar":"أحد أكبر التحديات في أنظمة SaaS للمطاعم هو ربط المبيعات بالمخزون. عندما يبيع الكاشير ''لاتيه''، يجب أن يخصم النظام 15 جراماً من القهوة، و200 مل من الحليب، وكوباً ورقياً واحداً في نفس اللحظة. هندسة قاعدة بيانات (PostgreSQL) تربط المنتجات النهائية بالمواد الخام دون التسبب باختناقات في الأداء وقت الذروة تطلب تحسيناً دقيقاً للاستعلامات."}},{"type":"h2","text":{"en":"Offline-First and Reliability","ar":"دعم العمل بدون إنترنت والموثوقية"}},{"type":"p","text":{"en":"Coffee shops can''t stop operating if the internet goes down. Leveraging modern web capabilities, I ensured the core POS functionalities remained active offline, syncing seamlessly with the server once the connection is restored. This robust architecture is what makes Ahwa a true OS for the F&B industry.","ar":"لا يمكن للمقهى أن يتوقف عن العمل إذا انقطع الإنترنت. باستخدام التقنيات الحديثة للويب، ضمنت أن تظل الوظائف الأساسية للكاشير تعمل بدون إنترنت (Offline)، ليتم مزامنة البيانات بسلاسة مع السيرفر بمجرد عودة الاتصال. هذه البنية التحتية القوية هي ما يجعل Ahwa نظام تشغيل حقيقي لقطاع الأغذية والمشروبات."}}]'::jsonb,
    '["SaaS","Next.js","PostgreSQL","System Design"]'::jsonb, NULL, '2024-05-20T14:30:00Z'
  );
INSERT INTO blog_posts (
    slug, status, title_en, title_ar, summary_en, summary_ar, content_en, content_ar, tags, cover_image, published_date
  ) VALUES (
    'technical-seo-more-than-meta-tags', 'published',
    'Why Technical SEO is the Secret to Google Page 1 Rankings', 'لماذا الـ SEO التقني هو السر الحقيقي لتصدر الصفحة الأولى في جوجل',
    'A look into how extreme performance tuning and proper schema injection helped GrowLik dominate search results.', 'نظرة على كيف ساعد التحسين الجذري للأداء وحقن البيانات المنظمة موقع GrowLik في السيطرة على نتائج البحث.',
    '[{"type":"p","text":{"en":"Most developers think SEO is just about adding `<title>` and `<meta name=''description''>` tags. While content is king, Google’s crawler heavily penalizes slow, poorly structured websites. In my work on the GrowLik platform, Technical SEO was the absolute priority.","ar":"يعتقد معظم المطورين أن الـ SEO يقتصر على إضافة وسوم `<title>` و `<meta>`. رغم أهمية المحتوى، إلا أن عناكب جوجل تعاقب بشدة المواقع البطيئة وذات الهيكلة السيئة. في عملي على منصة GrowLik، كان الـ Technical SEO هو الأولوية المطلقة."}},{"type":"h2","text":{"en":"Performance as a Ranking Factor","ar":"الأداء كعامل أساسي في الترتيب"}},{"type":"p","text":{"en":"Google uses Core Web Vitals (LCP, FID, CLS) to rank pages. For GrowLik, I utilized Next.js Server-Side Rendering (SSR) and aggressive image optimization to ensure a 100/100 Lighthouse score. The site loads almost instantly, keeping bounce rates extremely low.","ar":"يستخدم جوجل مؤشرات أداء الويب الأساسية (Core Web Vitals) لترتيب الصفحات. بالنسبة لـ GrowLik، استخدمت التصيير من جهة الخادم (SSR) في Next.js والتحسين القوي للصور لضمان تحقيق تقييم 100/100 في Lighthouse. الموقع يحمل بشكل شبه فوري، مما يبقي معدلات الارتداد (Bounce Rates) منخفضة جداً."}},{"type":"h2","text":{"en":"Structured Data (Schema.org)","ar":"البيانات المنظمة (Structured Data)"}},{"type":"p","text":{"en":"To give Google exact context, I injected dynamic JSON-LD structured data into every page. This translates raw text into semantic entities that search engines understand perfectly. Combined with custom GTM (Google Tag Manager) tracking, these engineering practices propelled the site to the #1 spot on Google''s first page.","ar":"لإعطاء جوجل السياق الدقيق، قمت بحقن بيانات منظمة ديناميكية (JSON-LD) في كل صفحة. هذا يترجم النصوص العادية إلى كيانات دلالية تفهمها محركات البحث تماماً. وبدمج ذلك مع تتبع مخصص عبر GTM، دفعت هذه الممارسات الهندسية الموقع لتصدر المركز الأول في الصفحة الأولى لجوجل."}}]'::jsonb, '[{"type":"p","text":{"en":"Most developers think SEO is just about adding `<title>` and `<meta name=''description''>` tags. While content is king, Google’s crawler heavily penalizes slow, poorly structured websites. In my work on the GrowLik platform, Technical SEO was the absolute priority.","ar":"يعتقد معظم المطورين أن الـ SEO يقتصر على إضافة وسوم `<title>` و `<meta>`. رغم أهمية المحتوى، إلا أن عناكب جوجل تعاقب بشدة المواقع البطيئة وذات الهيكلة السيئة. في عملي على منصة GrowLik، كان الـ Technical SEO هو الأولوية المطلقة."}},{"type":"h2","text":{"en":"Performance as a Ranking Factor","ar":"الأداء كعامل أساسي في الترتيب"}},{"type":"p","text":{"en":"Google uses Core Web Vitals (LCP, FID, CLS) to rank pages. For GrowLik, I utilized Next.js Server-Side Rendering (SSR) and aggressive image optimization to ensure a 100/100 Lighthouse score. The site loads almost instantly, keeping bounce rates extremely low.","ar":"يستخدم جوجل مؤشرات أداء الويب الأساسية (Core Web Vitals) لترتيب الصفحات. بالنسبة لـ GrowLik، استخدمت التصيير من جهة الخادم (SSR) في Next.js والتحسين القوي للصور لضمان تحقيق تقييم 100/100 في Lighthouse. الموقع يحمل بشكل شبه فوري، مما يبقي معدلات الارتداد (Bounce Rates) منخفضة جداً."}},{"type":"h2","text":{"en":"Structured Data (Schema.org)","ar":"البيانات المنظمة (Structured Data)"}},{"type":"p","text":{"en":"To give Google exact context, I injected dynamic JSON-LD structured data into every page. This translates raw text into semantic entities that search engines understand perfectly. Combined with custom GTM (Google Tag Manager) tracking, these engineering practices propelled the site to the #1 spot on Google''s first page.","ar":"لإعطاء جوجل السياق الدقيق، قمت بحقن بيانات منظمة ديناميكية (JSON-LD) في كل صفحة. هذا يترجم النصوص العادية إلى كيانات دلالية تفهمها محركات البحث تماماً. وبدمج ذلك مع تتبع مخصص عبر GTM، دفعت هذه الممارسات الهندسية الموقع لتصدر المركز الأول في الصفحة الأولى لجوجل."}}]'::jsonb,
    '["SEO","Lighthouse","Core Web Vitals","Next.js"]'::jsonb, NULL, '2024-06-10T09:15:00Z'
  );

-- SERVICES
DELETE FROM services;
INSERT INTO services (
    "order", status, slug, icon, keyword_en, keyword_ar, title_en, title_ar,
    description_en, description_ar, includes_en, includes_ar
  ) VALUES (
    1, 'published', 'saas-development', 'code',
    NULL, NULL,
    'SaaS & Custom Web Applications', 'بناء منصات الـ SaaS والأنظمة المخصصة',
    NULL, NULL,
    '[]'::jsonb, '[]'::jsonb
  );
INSERT INTO services (
    "order", status, slug, icon, keyword_en, keyword_ar, title_en, title_ar,
    description_en, description_ar, includes_en, includes_ar
  ) VALUES (
    2, 'published', 'ecommerce-development', 'shopping-cart',
    NULL, NULL,
    'E-Commerce Development & Customization', 'تطوير وتخصيص المتاجر الإلكترونية',
    NULL, NULL,
    '[]'::jsonb, '[]'::jsonb
  );
INSERT INTO services (
    "order", status, slug, icon, keyword_en, keyword_ar, title_en, title_ar,
    description_en, description_ar, includes_en, includes_ar
  ) VALUES (
    3, 'published', 'project-rescue', 'wrench',
    NULL, NULL,
    'Project Rescue & Technical Optimization', 'إنقاذ المشاريع والتحسين التقني',
    NULL, NULL,
    '[]'::jsonb, '[]'::jsonb
  );
INSERT INTO services (
    "order", status, slug, icon, keyword_en, keyword_ar, title_en, title_ar,
    description_en, description_ar, includes_en, includes_ar
  ) VALUES (
    4, 'published', 'technical-seo', 'search',
    NULL, NULL,
    'Technical SEO & Performance', 'تحسين محركات البحث التقني والأداء',
    NULL, NULL,
    '[]'::jsonb, '[]'::jsonb
  );
